version: '3'
services:
  mysql-1:
    image: ${MYSQL_IMAGE:-mysql:5.7}
    ports:
      - ${MYSQL_HOST:-127.0.0.1}:${MYSQL_PORT:-3306}:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    # MariaDB >= 10.0.12 doesn't enable Performance Schema by default so we need to do it manually
    # https://mariadb.com/kb/en/mariadb/performance-schema-overview/#activating-the-performance-schema
    command: --performance-schema --secure-file-priv=""
    #volumes:
    #  - ./test/schema/:/docker-entrypoint-initdb.d/:rw
  mysql-2:
    image: ${MYSQL_IMAGE:-mysql:5.7}
    ports:
      - ${MYSQL_HOST:-127.0.0.1}:${MYSQL_PORT:-3307}:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    # MariaDB >= 10.0.12 doesn't enable Performance Schema by default so we need to do it manually
    # https://mariadb.com/kb/en/mariadb/performance-schema-overview/#activating-the-performance-schema
    command: --performance-schema --secure-file-priv=""
    #volumes:
    #  - ./test/schema/:/docker-entrypoint-initdb.d/:rw
  mysql-3:
    image: ${MYSQL_IMAGE:-mysql:5.6}
    ports:
      - ${MYSQL_HOST:-127.0.0.1}:${MYSQL_PORT:-3308}:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    # MariaDB >= 10.0.12 doesn't enable Performance Schema by default so we need to do it manually
    # https://mariadb.com/kb/en/mariadb/performance-schema-overview/#activating-the-performance-schema
    command: --performance-schema --secure-file-priv=""
    #volumes:
    #  - ./test/schema/:/docker-entrypoint-initdb.d/:rw
  mysql-4:
    image: ${MYSQL_IMAGE:-mysql:5.5}
    ports:
      - ${MYSQL_HOST:-127.0.0.1}:${MYSQL_PORT:-3309}:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    # MariaDB >= 10.0.12 doesn't enable Performance Schema by default so we need to do it manually
    # https://mariadb.com/kb/en/mariadb/performance-schema-overview/#activating-the-performance-schema
    command: --performance-schema --secure-file-priv=""
    #volumes:
    #  - ./test/schema/:/docker-entrypoint-initdb.d/:rw
